import "./globals.css";
import NavBar from "./components/NavBar";
import axios from "axios";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./Provider";
import UserData from "./api/_store/UserData";

import { ChatBox } from "./components/ChatBox";

export const metadata = {
  title: "Application of stage",
  description: "Generated by create next app",
};
axios.defaults.baseURL = "http://localhost:3000/";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className=" text-black">
        <AuthProvider>
          <div className="relative h-screen">
            <Toaster position="top-center" />
            <UserData />
            <NavBar />
            <div className="">{children}</div>
            {/* <ChatBox/> */}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
